"""
Branch 3 on every backtest -- orchestrator.profit_bars_every_backtest.enabled
(off by default; requires orchestrator.profit_bars_file.enabled AND
orchestrator.regroup_record.enabled, hence specialist_readers). Operator-approved
2026-09-24; delivery_plan_v26.md target row "8 · profit bars ... one file, every
backtest, stop rule". Code-review fixes (same day) are marked [CR n] below; each
of those tests fails on 7675be94.

Target order: judge (grid) -> learn (readers) -> profit check (graded right
after protocol_execution, never paused there) -> regroup + record (memory holds
the per-variant result) -> decide (profit_bars_reached raised in the route after
regroup_record, before the grid route). A resume continues forward.

Covers:
  1. The flag reader and its dependencies ([CR 1] regroup_record required),
     enforced in run_loop's pre-flight.
  2. Flag-off byte-identity: golden promote-path outputs generated by master
     83794d9a ([CR 8], tests/fixtures/profit_bars_golden/), and a run_loop pass
     that reads/writes nothing new.
  3. Candidates = this attempt's grid columns, not files on disk ([CR 3]); stale
     evaluation cleared at protocol_execution entry ([CR 3]); invalidated trials
     never graded ([CR 7]).
  4. avg_daily_return_min computed from the per-window equity files, exact value,
     NOT_EVALUABLE on a missing file, and a real PASS without any monkeypatch
     ([CR 4]). Operator decision 2026-09-24: avg_daily_return_min and
     max_drawdown_pct_max are judged on the equal-weight portfolio of all coins
     (hand-computed 2-coin fixture, day intersection, per-window drawdown, one
     losing coin inside a passing portfolio); trade_count_min stays the per-coin
     minimum; every flag-on bar row records its `basis`.
  5. The stop: raised after regroup_record, protocol_execution completes, memory
     recorded first; resume goes forward without re-running backtests or
     re-pausing ([CR 1+2]); stays off when nothing passes; idea_status and the
     ledger untouched.
  6. Campaign memory: per-variant profit_bars when on, null+reason when off.
  7. Promote path: skipped only for a run holding its own every_backtest
     evaluation ([CR 6]); the flag read is inside the try ([CR 10]).
  8. A malformed bars file fails loud.
  9. One scope constant, owned by tools/campaign_memory.py ([CR 9]); RUNBOOK's
     separate not-validated resolution ([CR 5]).
"""
import asyncio
import json
import sys
import tempfile
from pathlib import Path

import jsonschema
import pytest

# D-063: these tests drive the loop through the reader stage, which reads the two design docs.
pytestmark = pytest.mark.usefixtures("reader_docs")
import yaml

SR_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(SR_ROOT / "workflow"))
sys.path.insert(0, str(SR_ROOT / "tools"))
sys.path.insert(0, str(Path(__file__).parent / "fixtures" / "profit_bars_golden"))

import run_phase1_research as rpr  # noqa: E402
import run_campaign as rc  # noqa: E402
import campaign_memory as cm  # noqa: E402
import golden_harness  # noqa: E402

from test_e058_s2a_regroup_record import (  # noqa: E402
    ALL_ON, RUN_ID, _seed, _grid, _memory, _memory_path, _set_orchestrator, _fake_llm,
    REPORT_CATEGORIES, _minimal_run_at)

PB = {"profit_bars_file": {"enabled": True}, "profit_bars_every_backtest": {"enabled": True}}
FULL_ON = {**ALL_ON, **PB}  # grid + reports + readers + regroup_record + both profit flags
VARIANT_LOOP_ON = {"config_direct_authoring": {"enabled": True}, "variant_loop": {"enabled": True}}
GOLDEN_DIR = Path(__file__).parent / "fixtures" / "profit_bars_golden"

_VALID_BARS = {
    "sharpe_min": 0.5,
    "max_drawdown_pct_max": 25.0,
    "avg_daily_return_min": 0.0005,
    "trade_count_min": 30,
    "deflated_sharpe_threshold": 0.95,
    "target_instrument_set": ["BTCUSDT", "ETHUSDT"],
    "ratified_by": None,
    "ratified_at": None,
}
_SCHEMA = json.loads((SR_ROOT / "workflow_artifacts" / "schemas" /
                      "campaign_memory.schema.json").read_text(encoding="utf-8"))


@pytest.fixture(autouse=True)
def _stub_tbot_python(monkeypatch):
    monkeypatch.setattr(rpr, "_resolve_tbot_python", lambda: Path("stub-python"))


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------

def _write_bars(doc: dict | None = None) -> Path:
    path = rpr.ROOT / "config" / "profitability_bars.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(_VALID_BARS if doc is None else doc), encoding="utf-8")
    return path


def _write_equity(results_root: Path, window_run_id: str, closes: list,
                  warmup_rows: int = 2, bars_per_day: int = 2) -> None:
    """portfolio_states.csv for one window: `warmup_rows` NOT_READY rows, then
    `bars_per_day` bars per day whose LAST bar carries that day's close. The
    earlier bars carry the midpoint of the previous close and this close: a
    realistic intraday path (no dip below both closes, so it adds no bar-level
    drawdown), but a daily return taken from them would differ from the one
    taken from the last bar, so the last-bar rule is still exercised."""
    d = results_root / window_run_id
    d.mkdir(parents=True, exist_ok=True)
    lines = ["timestamp,regime,postRebalance_total_value,total_portfolio_value"]
    for i in range(warmup_rows):
        lines.append(f"2020-01-01 0{i}:00:00,NOT_READY,999999.0,999999.0")
    for day, close in enumerate(closes):
        date = f"2020-01-{day + 2:02d}"
        mid = (closes[max(day - 1, 0)] + close) / 2
        for b in range(bars_per_day - 1):
            lines.append(f"{date} {b:02d}:00:00,trend,{mid},{mid}")
        lines.append(f"{date} 23:00:00, trend ,{close},{close}")
    (d / "portfolio_states.csv").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _pr(tag: str, results_root: Path, good: bool) -> dict:
    """A protocol_result with 2 symbols x 2 windows, each window backed by an
    equity file. good=True clears every bar (DSR against _seed_dsr_ledger);
    good=False fails them."""
    results = []
    for sym in ("BTCUSDT", "ETHUSDT"):
        for w in ("w1", "w2"):
            wid = f"{tag}-{sym}-{w}"
            growth = 1.002 if good else 0.995
            _write_equity(results_root, wid, [1000.0 * growth ** k for k in range(8)])
            results.append({"symbol": sym, "window": w, "run_id": wid,
                            "core": {"sharpe": 1.4 if good else -1.0}})
    pss = ({"BTCUSDT": {"median_sharpe": 1.5, "max_abs_drawdown_pct": 10.0, "min_trade_count": 50},
            "ETHUSDT": {"median_sharpe": 1.3, "max_abs_drawdown_pct": 12.0, "min_trade_count": 60}}
           if good else
           {"BTCUSDT": {"median_sharpe": -1.0, "max_abs_drawdown_pct": 40.0, "min_trade_count": 3},
            "ETHUSDT": {"median_sharpe": -0.5, "max_abs_drawdown_pct": 30.0, "min_trade_count": 5}})
    return {"verdict": "promote" if good else "kill", "results": results,
            "per_symbol_summary": pss,
            "protocol_file": str(rpr.ROOT / "protocols" / "p.json")}


def _seed_dsr_ledger() -> None:
    """Append 10 real-Sharpe trial rows from other runs so the DSR is computable:
    trial Sharpes spread around 0, so a candidate at ~1.4 deflates to ~1.0."""
    state = rpr.load_yaml(rpr.CAMPAIGN_STATE_PATH) if rpr.CAMPAIGN_STATE_PATH.exists() else {
        "campaign_id": "t", "runs": [], "trial_sharpes": []}
    state.setdefault("trial_sharpes", []).extend(
        {"trial_id": f"run_{800 + i}", "source": "backtest", "statistic_valid": "sharpe",
         "sharpe": round(-0.25 + 0.05 * i, 2), "forecast_hash": f"fh-ledger-{i}"}
        for i in range(10))
    rpr.save_yaml(rpr.CAMPAIGN_STATE_PATH, state)


def _single_run(good: bool, idea_status: str = "refuted", pending: str = "regroup_record") -> Path:
    """Variant loop off: the grid's single column is run_id."""
    run_dir = _seed(idea_status=idea_status, pending=pending)
    rpr.save_yaml(run_dir / "artifacts" / "protocol_result.yaml",
                  _pr("single", run_dir / "results", good))
    _seed_dsr_ledger()
    return run_dir


def _variant_run(graded: dict, idea_status: str = "refuted", stale: dict | None = None) -> Path:
    """Variant loop on. `graded` = {variant_id: good?} are this attempt's grid
    columns; `broken` is validated but has no column (its backtest failed this
    attempt) -- `stale` may still leave an old protocol_result on disk for it;
    `asset` was not tested by the data gate."""
    run_dir = _seed(idea_status="refuted", variant_loop=True)
    arts = run_dir / "artifacts"
    index = {vid: {"status": "validated",
                   "config_path": f"artifacts/variants/{vid}/strategy_config.json"}
             for vid in list(graded) + ["broken"]}
    index["asset"] = {"status": "not_tested", "reason": "patch application failed: /x"}
    rpr.save_yaml(arts / "variants" / "index.yaml", {"variants": index})
    for vid, good in graded.items():
        rpr.save_yaml(arts / "variants" / vid / "protocol_result.yaml",
                      _pr(vid, run_dir / "variants" / vid / "results", good))
    broken = arts / "variants" / "broken" / "protocol_result.yaml"
    if stale:
        rpr.save_yaml(broken, _pr("broken", run_dir / "variants" / "broken" / "results",
                                  stale["good"]))
    elif broken.exists():
        broken.unlink()
    grid = _grid(list(graded), idea_status)
    rpr.save_yaml(arts / "grid_evaluation.yaml", grid)
    rpr.save_yaml(arts / "idea_status.yaml", rpr._build_idea_status_artifact(grid, RUN_ID))
    rows = [{"trial_id": f"{RUN_ID}:{vid}", "source": "backtest", "sharpe": 0.3,
             "forecast_hash": f"fh-{vid}"} for vid in graded]
    rows.append({"trial_id": f"{RUN_ID}:broken", "source": "backtest_failed", "sharpe": None,
                 "forecast_hash": "fh-broken"})
    rpr.save_yaml(rpr.CAMPAIGN_STATE_PATH, {"campaign_id": "t", "runs": [], "trial_sharpes": rows})
    _seed_dsr_ledger()
    return run_dir


def _state(run_dir: Path) -> dict:
    return rpr.load_yaml(run_dir / "pipeline_state.yaml")


def _pbe(run_dir: Path) -> dict:
    return yaml.safe_load((run_dir / "artifacts" / "profit_bars_evaluation.yaml")
                          .read_text(encoding="utf-8"))


def _loop(monkeypatch, orchestrator: dict, *, good: bool | None = None,
          idea_status: str = "refuted", fresh: bool = True):
    """run_loop from protocol_execution (fresh=True) or from wherever the state
    stands (fresh=False, e.g. a resume). The backtest itself is stubbed: its
    artifacts are pre-seeded. Returns (run_dir, stages, reader_calls)."""
    _set_orchestrator(orchestrator)
    if fresh:
        run_dir = _minimal_run_at(rpr.ROOT, RUN_ID, "protocol_execution")
        _seed(pending="protocol_execution", idea_status=idea_status)
        rpr._ensure_protocol_ref_pinned(run_dir, RUN_ID,
                                        {"protocol_ref": f"protocols/{RUN_ID}_pinned.json"})
        rpr.save_yaml(run_dir / "handoffs" / "backtest_spec_to_protocol_execution.yaml",
                      {"required_inputs": [], "deliverables": []})
        if good is not None:
            rpr.save_yaml(run_dir / "artifacts" / "protocol_result.yaml",
                          _pr("single", run_dir / "results", good))
            _seed_dsr_ledger()
        for c in REPORT_CATEGORIES:
            (run_dir / "artifacts" / "proposals" / f"{c}.yaml").unlink()
    else:
        run_dir = rpr.ROOT / "runs" / RUN_ID
    stages, calls = [], []

    async def _record(stage_name, run_id, retry_context=None):
        stages.append(stage_name)
    monkeypatch.setattr(rpr, "async_invoke_agent", _record)
    monkeypatch.setattr(rpr, "_invoke_reader_llm", _fake_llm(calls=calls))
    rpr.run_loop(RUN_ID)
    return run_dir, stages, calls


# ---------------------------------------------------------------------------
# 1. The flag reader and its dependencies
# ---------------------------------------------------------------------------

def test_flag_false_when_absent_or_off():
    _set_orchestrator(None)
    assert rpr._profit_bars_every_backtest_enabled() is False
    _set_orchestrator({**ALL_ON, "profit_bars_file": {"enabled": True}})
    assert rpr._profit_bars_every_backtest_enabled() is False


def test_flag_true_with_all_dependencies_on():
    _set_orchestrator(FULL_ON)
    assert rpr._profit_bars_every_backtest_enabled() is True


@pytest.mark.parametrize("bad", ["true", None, 1])
def test_flag_non_bool_raises(bad):
    _set_orchestrator({**FULL_ON, "profit_bars_every_backtest": {"enabled": bad}})
    with pytest.raises(ValueError, match="not a real"):
        rpr._profit_bars_every_backtest_enabled()


def test_flag_on_without_profit_bars_file_raises():
    _set_orchestrator({**ALL_ON, "profit_bars_every_backtest": {"enabled": True}})
    with pytest.raises(ValueError, match="requires orchestrator.profit_bars_file.enabled=true"):
        rpr._profit_bars_every_backtest_enabled()


def test_cr1_flag_on_without_regroup_record_raises():
    """[CR 1] The stop is raised after regroup_record, so the flag requires it."""
    _set_orchestrator(PB)
    with pytest.raises(ValueError, match="requires orchestrator.regroup_record.enabled=true"):
        rpr._profit_bars_every_backtest_enabled()


@pytest.mark.parametrize("orchestrator", [
    {**ALL_ON, "profit_bars_every_backtest": {"enabled": True}},  # no profit_bars_file
    PB,  # no regroup_record / readers
])
def test_run_loop_preflight_fails_before_any_spend(monkeypatch, orchestrator):
    _set_orchestrator(orchestrator)
    run_dir = _minimal_run_at(rpr.ROOT, RUN_ID, "protocol_execution")
    _seed(pending="protocol_execution")
    invoked = []

    async def _record(stage_name, run_id, retry_context=None):
        invoked.append(stage_name)
    monkeypatch.setattr(rpr, "async_invoke_agent", _record)
    rpr.run_loop(RUN_ID)
    state = _state(run_dir)
    assert invoked == []
    assert state["status"] == "failed" and "requires" in state["last_error"]
    assert state["pending_stage"] == "protocol_execution"


# ---------------------------------------------------------------------------
# 2. Flag-off byte-identity
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("scenario", sorted(golden_harness.scenarios()))
def test_cr8_promote_path_matches_master_golden_outputs(scenario):
    """[CR 8] promotion_audit.yaml (incl. the variant-loop per_variant branch) and
    the promote-path profit_bars_evaluation.yaml, generated by master 83794d9a
    (see golden_harness.py), are byte-identical under the current code with the
    new flag absent."""
    out = golden_harness.run_scenario(rpr, scenario, Path(tempfile.mkdtemp()))
    expected_files = sorted(p.name for p in (GOLDEN_DIR / scenario).iterdir())
    assert sorted(out) == expected_files
    for fname in expected_files:
        assert out[fname] == (GOLDEN_DIR / scenario / fname).read_text(encoding="utf-8"), fname


def test_flag_off_run_loop_reads_and_writes_nothing_new(monkeypatch):
    """No bars file exists at all: any read of it would fail the run."""
    run_dir, _stages, _calls = _loop(monkeypatch, ALL_ON)
    state = _state(run_dir)
    assert state["completed_stages"][-3:] == ["protocol_execution", "specialist_readers", "regroup_record"]
    assert state["pending_stage"] == "completed_rejected"
    assert not (run_dir / "artifacts" / "profit_bars_evaluation.yaml").exists()
    assert "profit_bars_reached" not in (state.get("flags") or {})
    assert "profit_bars_stop_evaluation" not in state
    e = _memory()["runs"][RUN_ID]
    assert e["profit_bars"] is None and e["profit_bars_reason"] == "not evaluated before regroup"


# ---------------------------------------------------------------------------
# 3. Candidates: this attempt only
# ---------------------------------------------------------------------------

def test_every_tested_variant_graded_on_its_own_numbers():
    _set_orchestrator({**FULL_ON, **VARIANT_LOOP_ON})
    _write_bars()
    run_dir = _variant_run({"base": False, "design": True})
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    assert ev == _pbe(run_dir) and ev["scope"] == cm.PROFIT_BARS_SCOPE_EVERY_BACKTEST
    assert sorted(ev["variants"]) == ["asset", "base", "broken", "design"]
    assert ev["variants"]["design"]["trial_id"] == f"{RUN_ID}:design"
    design = {b["name"]: b for b in ev["variants"]["design"]["bars"]}
    base = {b["name"]: b for b in ev["variants"]["base"]["bars"]}
    assert design["sharpe_min"]["actual"] == 1.4 and base["trade_count_min"]["actual"] == 3
    for vid in ("asset", "broken"):
        assert ev["variants"][vid]["result"] == "NOT_TESTED" and ev["variants"][vid]["bars"] == []
    assert ev["passing"] == ["design"] and ev["result"] == "PASS"
    assert "stop_raised" not in ev  # the evaluation never decides the stop


def test_cr3_stale_protocol_result_of_a_failed_variant_is_not_graded():
    """[CR 3] `broken` failed on this attempt (no grid column) but an older,
    passing protocol_result.yaml is still on disk: it must not be graded."""
    _set_orchestrator({**FULL_ON, **VARIANT_LOOP_ON})
    _write_bars()
    run_dir = _variant_run({"base": False}, stale={"good": True})
    assert (run_dir / "artifacts" / "variants" / "broken" / "protocol_result.yaml").exists()
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    assert ev["variants"]["broken"]["result"] == "NOT_TESTED"
    assert ev["passing"] == [] and ev["result"] == "FAIL"


def test_cr3_missing_grid_fails_loud():
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    (run_dir / "artifacts" / "grid_evaluation.yaml").unlink()
    with pytest.raises(FileNotFoundError, match="grid_evaluation.yaml"):
        rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)


@pytest.mark.parametrize("flag_on", [True, False])
def test_cr3_stale_evaluation_cleared_at_protocol_execution_entry(monkeypatch, flag_on):
    """[CR 3] Under the flag, protocol_execution deletes the previous attempt's
    profit_bars_evaluation.yaml first; flag off, nothing is deleted."""
    _set_orchestrator(FULL_ON if flag_on else ALL_ON)
    run_dir = _minimal_run_at(rpr.ROOT, RUN_ID, "protocol_execution")
    _seed(pending="protocol_execution")
    stale = run_dir / "artifacts" / "profit_bars_evaluation.yaml"
    rpr.save_yaml(stale, {"run_id": RUN_ID, "scope": "every_backtest", "passing": ["old"]})

    class _Failed:
        returncode, stdout, stderr = 1, "", "boom"
    monkeypatch.setattr(rpr.subprocess, "run", lambda *a, **k: _Failed())
    with pytest.raises(RuntimeError):
        asyncio.run(rpr.run_tool_worker("protocol_execution", RUN_ID))
    assert stale.exists() is (not flag_on)


def test_cr7_invalidated_trial_is_never_graded_or_passing():
    """[CR 7] A conformance violation invalidated design's trial row: even with
    passing numbers it is INVALIDATED, not graded, not in `passing`."""
    _set_orchestrator({**FULL_ON, **VARIANT_LOOP_ON})
    _write_bars()
    run_dir = _variant_run({"base": False, "design": True})
    assert rpr._mark_trial_invalidated(f"{RUN_ID}:design", "conformance") is True
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    assert ev["variants"]["design"]["result"] == "INVALIDATED"
    assert ev["variants"]["design"]["bars"] == []
    assert ev["passing"] == [] and ev["result"] == "FAIL"


# ---------------------------------------------------------------------------
# 4. avg_daily_return_min
# ---------------------------------------------------------------------------

def _write_equity_days(results_root: Path, window_run_id: str, closes: dict) -> None:
    """portfolio_states.csv with one warm-up row, then for each {"2020-MM-DD": v}
    the day's bars: v a float -> one bar at 23:00 carrying the close; v a list ->
    its earlier values at 01:00, 02:00, ... (intraday bars) and its LAST value at
    23:00 (the close)."""
    d = results_root / window_run_id
    d.mkdir(parents=True, exist_ok=True)
    lines = ["timestamp,regime,postRebalance_total_value",
             "2019-12-31 23:00:00,NOT_READY,999999.0"]
    for date, v in closes.items():
        vals = v if isinstance(v, list) else [v]
        lines += [f"{date} {h + 1:02d}:00:00,trend,{x}" for h, x in enumerate(vals[:-1])]
        lines.append(f"{date} 23:00:00,trend,{vals[-1]}")
    (d / "portfolio_states.csv").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _days(closes: list, first: int = 2, month: int = 1) -> dict:
    return {f"2020-{month:02d}-{first + i:02d}": c for i, c in enumerate(closes)}


def _pm(root: Path, spec: dict) -> dict:
    """_portfolio_profit_metrics on {(coin, window): {date: close}} equity files."""
    results = []
    for (sym, win), closes in spec.items():
        wid = f"{sym}-{win}"
        _write_equity_days(root / "results", wid, closes)
        results.append({"symbol": sym, "window": win, "run_id": wid})
    return rpr._portfolio_profit_metrics(root, {"results": results})


def _ok(m: dict) -> None:
    assert m.get("not_evaluable_reason") is None, m.get("not_evaluable_reason")


def _not_evaluable(m: dict, fragment: str) -> None:
    assert m["avg_daily_return"][0] is None and m["max_drawdown_pct"][0] is None
    assert fragment in m["not_evaluable_reason"], m["not_evaluable_reason"]


def test_portfolio_return_and_drawdown_hand_computed_two_coins(tmp_path):
    """A: 100,120,90,96 -> 1, 1.2, 0.9, 0.96. B: 100,100,110,99 -> 1, 1.0, 1.1, 0.99.
    Equal-weight portfolio = 1, 1.1, 1.0, 0.975. Daily returns 0.1, -1/11, -0.025.
    Drawdown: peak 1.1 -> trough 0.975 = 100 * (1 - 0.975/1.1) = 11.363636..%."""
    m = _pm(tmp_path, {("A", "w1"): _days([100.0, 120.0, 90.0, 96.0]),
                       ("B", "w1"): _days([100.0, 100.0, 110.0, 99.0])})
    _ok(m)
    adr, adr_note = m["avg_daily_return"]
    dd, dd_note = m["max_drawdown_pct"]
    assert adr == round((0.1 + (1.0 / 1.1 - 1.0) + (0.975 / 1.0 - 1.0)) / 3, 8)
    assert dd == round(100.0 * (1.0 - 0.975 / 1.1), 6)
    assert "equal-weight portfolio of 2 coin(s) ['A', 'B']" in adr_note
    assert "worst WINDOW 'w1', not the worst coin" in dd_note


_TEN = [f"2020-01-{d:02d}" for d in range(2, 12)]


def test_portfolio_day_intersection_and_note_counts_add_up(tmp_path):
    """[CR 7] A has 10 days (01-02..01-11); B lacks 01-07. Union 10, common 9
    (coverage 0.9, exactly the floor). A's 01-07 value (500) is never used. Common
    days 02..06 and 08..11: 7 consecutive-day returns, 1 step across the gap."""
    a = {d: 100.0 * 1.01 ** i for i, d in enumerate(_TEN)}
    a["2020-01-07"] = 500.0
    b = {d: 200.0 for d in _TEN if d != "2020-01-07"}
    m = _pm(tmp_path, {("A", "w1"): a, ("B", "w1"): b})
    _ok(m)
    idx = [i for i, d in enumerate(_TEN) if d != "2020-01-07"]
    v = {i: (1.01 ** i + 1.0) / 2 for i in idx}
    rets = [v[i] / v[i - 1] - 1.0 for i in idx if i - 1 in v]
    assert len(rets) == 7
    assert m["avg_daily_return"][0] == round(sum(rets) / 7, 8)
    note = m["avg_daily_return"][1]
    assert "days: 10 in the union of the coins' days = 9 common + 1 dropped" in note
    assert "9 common = 1 first day(s) + 7 daily return(s) + 1 multi-day step(s)" in note


def test_cr1_coverage_below_floor_is_not_evaluable(tmp_path):
    """[CR 1] B lacks 2 of 10 days: common 8 / union 10 = 0.8 < 0.9."""
    a = {d: 100.0 for d in _TEN}
    b = {d: 100.0 for d in _TEN if d not in ("2020-01-06", "2020-01-07")}
    m = _pm(tmp_path, {("A", "w1"): a, ("B", "w1"): b})
    _not_evaluable(m, "PORTFOLIO_MIN_COMMON_DAY_COVERAGE=0.9")
    assert "80.0%" in m["not_evaluable_reason"]
    assert rpr.PORTFOLIO_MIN_COMMON_DAY_COVERAGE == 0.9


def test_cr1_not_evaluable_reason_is_structured_not_only_the_note():
    """[CR 1] The bar row carries not_evaluable_reason and `reasons` names it."""
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    (run_dir / "results" / "single-ETHUSDT-w2" / "portfolio_states.csv").unlink()
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    v = ev["variants"][RUN_ID]
    bars = {b["name"]: b for b in v["bars"]}
    for name in ("avg_daily_return_min", "max_drawdown_pct_max"):
        assert bars[name]["result"] == "NOT_EVALUABLE"
        assert "no portfolio_states.csv" in bars[name]["not_evaluable_reason"]
        assert any(r.startswith(name) and "no portfolio_states.csv" in r for r in v["reasons"])
    assert "not_evaluable_reason" not in bars["sharpe_min"]
    assert ev["result"] == "FAIL"


def test_cr2_window_with_a_single_common_day_is_not_evaluable(tmp_path):
    """[CR 2] w2 has one common day: the bar is NOT_EVALUABLE, never skipped."""
    w1 = _days([100.0, 110.0, 121.0])
    w2 = {"2020-02-01": 100.0}
    m = _pm(tmp_path, {("A", "w1"): w1, ("B", "w1"): w1, ("A", "w2"): w2, ("B", "w2"): w2})
    _not_evaluable(m, "window 'w2' has 1 UTC day(s)")


def test_cr3_drawdown_is_measured_on_bars_so_intraday_drops_count(tmp_path):
    """[CR 3] Daily closes are flat at 100 for both coins, but on 01-03 at 01:00
    A is at 80 while B is at 100: portfolio 0.9, a 10% bar-level drawdown that
    daily closes would hide. The average daily return (on closes) stays 0."""
    a = {"2020-01-02": 100.0, "2020-01-03": [80.0, 100.0], "2020-01-04": 100.0}
    b = {"2020-01-02": 100.0, "2020-01-03": [100.0, 100.0], "2020-01-04": 100.0}
    m = _pm(tmp_path, {("A", "w1"): a, ("B", "w1"): b})
    _ok(m)
    assert m["max_drawdown_pct"][0] == pytest.approx(10.0, abs=1e-9)
    assert "on its 4 common bar(s)" in m["max_drawdown_pct"][1]
    assert m["avg_daily_return"][0] == 0.0


def test_cr3_bars_before_the_first_common_day_close_are_not_in_the_drawdown(tmp_path):
    """A dip earlier on the first common day happens before the portfolio's
    normalization close, so it is not part of the portfolio curve."""
    a = {"2020-01-02": [50.0, 100.0], "2020-01-03": 100.0}
    b = {"2020-01-02": [100.0, 100.0], "2020-01-03": 100.0}
    m = _pm(tmp_path, {("A", "w1"): a, ("B", "w1"): b})
    assert m["max_drawdown_pct"][0] == 0.0


def test_cr4_step_across_a_gap_is_not_a_daily_return(tmp_path):
    """[CR 4] No coin has 01-05 (coverage stays 1.0). 01-04 -> 01-06 is a two-day
    step (121 -> 50) and is not counted: returns 0.1, 0.1, 0.1 -> mean 0.1."""
    days = {"2020-01-02": 100.0, "2020-01-03": 110.0, "2020-01-04": 121.0,
            "2020-01-06": 50.0, "2020-01-07": 55.0}
    m = _pm(tmp_path, {("A", "w1"): days, ("B", "w1"): days})
    _ok(m)
    assert m["avg_daily_return"][0] == pytest.approx(0.1, abs=1e-8)
    assert "3 daily return(s) + 1 multi-day step(s) across a gap, not counted" \
        in m["avg_daily_return"][1]


def test_cr4_no_consecutive_common_days_is_not_evaluable(tmp_path):
    days = {"2020-01-02": 100.0, "2020-01-04": 110.0}
    m = _pm(tmp_path, {("A", "w1"): days, ("B", "w1"): days})
    _not_evaluable(m, "no two common days are consecutive")


def test_cr5_docs_say_first_common_day_not_window_start():
    header = (SR_ROOT / "config" / "profitability_bars.yaml").read_text(encoding="utf-8")
    assert "normalized to 1.0 at the first common day" in header
    assert "PORTFOLIO_MIN_COMMON_DAY_COVERAGE, currently 0.9" in header
    for text in (header, rpr._portfolio_profit_metrics.__doc__):
        assert "window start" not in text


def test_cr6_mixed_window_label_types_do_not_raise(tmp_path):
    """[CR 6] A YAML window label may load as an int (2024) next to a string."""
    w1, w2 = _days([100.0, 110.0]), _days([100.0, 90.0], first=10)
    m = _pm(tmp_path, {("A", 2024): w1, ("B", 2024): w1, ("A", "2024-02"): w2,
                       ("B", "2024-02"): w2})
    _ok(m)
    assert m["max_drawdown_pct"][0] == pytest.approx(10.0, abs=1e-9)
    assert "worst WINDOW '2024-02'" in m["max_drawdown_pct"][1]


def test_cr8_error_messages_use_the_portfolio_prefix(tmp_path):
    for root in (tmp_path / "results", tmp_path / "variants" / "v" / "results"):
        _write_equity_days(root, "x", _days([1.0, 2.0]))
    with pytest.raises(ValueError, match="^equal-weight portfolio: window run 'x'"):
        rpr._find_window_equity_file(tmp_path, "x")
    bad = tmp_path / "bad.csv"
    bad.write_text("timestamp,regime\n2020-01-01 00:00:00,trend\n", encoding="utf-8")
    with pytest.raises(ValueError, match="^equal-weight portfolio: .* lacks column"):
        rpr._window_daily_closes(bad)


def test_portfolio_drawdown_is_per_window_not_across_windows(tmp_path):
    """w1: 1000 -> 1500 -> 1200 (20% drawdown). w2 restarts from a fresh 1000:
    1000 -> 1100 -> 990 (10%). A curve concatenated across windows would read
    1500 -> 990 = 34%; the bar reads the worst WINDOW, 20%. Returns pool across
    both windows: 0.5, -0.2, 0.1, -0.1."""
    w1, w2 = _days([1000.0, 1500.0, 1200.0]), _days([1000.0, 1100.0, 990.0], first=10)
    m = _pm(tmp_path, {("A", "w1"): w1, ("B", "w1"): w1, ("A", "w2"): w2, ("B", "w2"): w2})
    assert m["max_drawdown_pct"][0] == pytest.approx(20.0, abs=1e-9)
    assert "worst WINDOW 'w1'" in m["max_drawdown_pct"][1]
    assert m["avg_daily_return"][0] == round((0.5 - 0.2 + 0.1 - 0.1) / 4, 8)


def test_portfolio_not_evaluable_when_coin_set_differs_between_windows(tmp_path):
    """A coin missing from one window means broken data (run_protocol writes every
    coin in every window)."""
    m = _pm(tmp_path, {("A", "w1"): _days([1.0, 2.0]), ("B", "w1"): _days([1.0, 2.0]),
                       ("A", "w2"): _days([1.0, 2.0])})
    _not_evaluable(m, "coin set differs")


def test_portfolio_duplicate_coin_window_or_missing_window_fails_loud(tmp_path):
    _write_equity_days(tmp_path / "results", "r1", _days([1.0, 2.0]))
    dup = {"results": [{"symbol": "A", "window": "w1", "run_id": "r1"},
                       {"symbol": "A", "window": "w1", "run_id": "r1"}]}
    with pytest.raises(ValueError, match="appears twice"):
        rpr._portfolio_profit_metrics(tmp_path, dup)
    with pytest.raises(ValueError, match="lacks symbol/window/run_id"):
        rpr._portfolio_profit_metrics(tmp_path, {"results": [{"symbol": "A", "run_id": "r1"}]})


def test_portfolio_not_evaluable_without_a_common_day(tmp_path):
    m = _pm(tmp_path, {("A", "w1"): _days([1.0, 2.0]), ("B", "w1"): _days([1.0, 2.0], first=20)})
    _not_evaluable(m, "has 0 UTC day(s)")


def test_cr4_avg_daily_return_not_evaluable_without_equity_files(tmp_path):
    pr = {"results": [{"symbol": "BTCUSDT", "window": "w1", "run_id": "absent"}]}
    m = rpr._portfolio_profit_metrics(tmp_path, pr)
    assert m["avg_daily_return"][0] is None and "no portfolio_states.csv" in m["avg_daily_return"][1]
    assert m["max_drawdown_pct"][0] is None
    assert rpr._portfolio_profit_metrics(tmp_path, {})["avg_daily_return"][0] is None


def test_cr4_malformed_equity_file_fails_loud(tmp_path):
    d = tmp_path / "results" / "x"
    d.mkdir(parents=True)
    (d / "portfolio_states.csv").write_text("timestamp,regime\n2020-01-01 00:00:00,trend\n",
                                            encoding="utf-8")
    with pytest.raises(ValueError, match="postRebalance_total_value"):
        rpr._portfolio_profit_metrics(
            tmp_path, {"results": [{"symbol": "BTCUSDT", "window": "w", "run_id": "x"}]})


def _one_coin_loses_run() -> Path:
    """Single run (variant loop off). BTCUSDT loses 0.1 %/day with a 30% per-coin
    drawdown in per_symbol_summary; ETHUSDT gains 0.4 %/day. Every other bar is
    the good fixture's."""
    run_dir = _single_run(good=True)
    pr = rpr.load_yaml(run_dir / "artifacts" / "protocol_result.yaml")
    for r in pr["results"]:
        growth = 0.999 if r["symbol"] == "BTCUSDT" else 1.004
        _write_equity(run_dir / "results", r["run_id"], [1000.0 * growth ** k for k in range(8)])
    pr["per_symbol_summary"]["BTCUSDT"]["max_abs_drawdown_pct"] = 30.0
    rpr.save_yaml(run_dir / "artifacts" / "protocol_result.yaml", pr)
    return run_dir


def test_one_coin_loses_portfolio_still_passes_without_monkeypatching():
    """The operator's reason for the change: BTCUSDT alone loses (worst-coin mean
    daily return -0.001, worst-coin drawdown 30% > 25%), yet the equal-weight
    portfolio clears every bar. A real PASS: no bar is monkeypatched."""
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _one_coin_loses_run()
    btc = rpr._window_daily_closes(run_dir / "results" / "single-BTCUSDT-w1" / "portfolio_states.csv")
    btc_closes = [btc[d] for d in sorted(btc)]
    assert btc_closes[-1] < btc_closes[0]  # the losing coin really loses
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    bars = {b["name"]: b for b in ev["variants"][RUN_ID]["bars"]}
    assert {b["result"] for b in bars.values()} == {"PASS"}
    expected = sum((0.999 ** k + 1.004 ** k) / (0.999 ** (k - 1) + 1.004 ** (k - 1)) - 1.0
                   for k in range(1, 8)) / 7
    assert bars["avg_daily_return_min"]["actual"] == round(expected, 8)
    assert bars["avg_daily_return_min"]["actual"] > 0.0005
    assert bars["max_drawdown_pct_max"]["actual"] == 0.0  # the portfolio never falls
    assert ev["passing"] == [RUN_ID] and ev["result"] == "PASS"
    # Flag-off promote path on the same run: worst coin, so the drawdown bar fails.
    off = {b["name"]: b for b in rpr._evaluate_profit_bars(run_dir, RUN_ID)["bars"]}
    assert off["max_drawdown_pct_max"]["actual"] == 30.0
    assert off["max_drawdown_pct_max"]["result"] == "FAIL"


def test_trade_count_still_per_coin_minimum():
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    pr = rpr.load_yaml(run_dir / "artifacts" / "protocol_result.yaml")
    pr["per_symbol_summary"]["ETHUSDT"]["min_trade_count"] = 10
    rpr.save_yaml(run_dir / "artifacts" / "protocol_result.yaml", pr)
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    tc = {b["name"]: b for b in ev["variants"][RUN_ID]["bars"]}["trade_count_min"]
    assert tc["actual"] == 10 and tc["result"] == "FAIL" and tc["basis"] == "worst_coin"
    assert ev["result"] == "FAIL"


_EXPECTED_BASIS = {
    "sharpe_min": "median_of_coin_median_sharpes",
    "deflated_sharpe_threshold": "deflated_sharpe_on_campaign_trial_ledger",
    "max_drawdown_pct_max": "portfolio_equal_weight_worst_window",
    "trade_count_min": "worst_coin",
    "avg_daily_return_min": "portfolio_equal_weight",
}


def test_basis_recorded_on_every_bar_in_the_artifact():
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    on_disk = _pbe(run_dir)["variants"][RUN_ID]["bars"]
    assert {b["name"]: b["basis"] for b in on_disk} == _EXPECTED_BASIS
    # The basis names match the definitions written in the bars-file header.
    header = (SR_ROOT / "config" / "profitability_bars.yaml").read_text(encoding="utf-8")
    for basis in _EXPECTED_BASIS.values():
        assert f"basis: {basis}\n" in header, basis


def test_cr4_real_pass_without_monkeypatching_any_bar():
    """[CR 4] Every bar, avg_daily_return_min included, genuinely evaluated."""
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    ev = rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    bars = {b["name"]: b for b in ev["variants"][RUN_ID]["bars"]}
    assert {b["result"] for b in bars.values()} == {"PASS"}
    assert bars["avg_daily_return_min"]["actual"] == pytest.approx(0.002, abs=1e-9)
    assert ev["passing"] == [RUN_ID] and ev["result"] == "PASS"


# ---------------------------------------------------------------------------
# 5. The stop, after regroup_record; resume goes forward
# ---------------------------------------------------------------------------

def test_cr1_stop_raised_after_regroup_record_not_at_protocol_execution(monkeypatch):
    """[CR 1+2] protocol_execution completes normally, the readers run, the
    memory records the passing variant, THEN the route pauses."""
    _write_bars()
    run_dir, stages, calls = _loop(monkeypatch, FULL_ON, good=True)
    state = _state(run_dir)
    assert stages == ["protocol_execution"] and len(calls) == 5  # readers ran
    assert state["completed_stages"][-2:] == ["protocol_execution", "specialist_readers"]
    assert state["pending_stage"] == "regroup_record"  # past protocol_execution
    assert state["status"] == "paused_for_human"
    assert state["flags"]["profit_bars_reached"] is True
    ev = _pbe(run_dir)
    assert state["profit_bars_stop_evaluation"] == ev["generated_at"]
    e = _memory()["runs"][RUN_ID]
    assert e["profit_bars"]["passing"] == [RUN_ID] and e["profit_bars_reason"] is None
    assert rc._classify_human_pause(run_dir, state) == "profit_bars_reached"


def test_cr2_resume_continues_forward_without_rerunning_backtests(monkeypatch):
    """[CR 2] After the operator clears the flag and resumes, the run re-enters
    regroup_record, does NOT re-pause on the same evaluation, never re-runs
    protocol_execution, and follows the grid's route."""
    _write_bars()
    run_dir, _s, _c = _loop(monkeypatch, FULL_ON, good=True)
    paused = _state(run_dir)
    assert paused["status"] == "paused_for_human" and paused["pending_stage"] == "regroup_record"
    ev_before =(run_dir / "artifacts" / "profit_bars_evaluation.yaml").read_bytes()
    rpr.update_state(path=run_dir, status="active", flags={"profit_bars_reached": False})
    _run_dir, stages, calls = _loop(monkeypatch, FULL_ON, fresh=False)
    state = _state(run_dir)
    assert stages == [] and calls == []  # no backtest, no reader re-run
    assert state["pending_stage"] == "completed_rejected"  # refuted grid -> rejected
    assert state["flags"]["profit_bars_reached"] is False
    assert (run_dir / "artifacts" / "profit_bars_evaluation.yaml").read_bytes() == ev_before
    assert state["completed_stages"][-1] == "regroup_record"


def test_stop_stays_off_when_nothing_passes(monkeypatch):
    _write_bars()
    run_dir, _s, _c = _loop(monkeypatch, FULL_ON, good=False)
    state = _state(run_dir)
    assert state["pending_stage"] == "completed_rejected"  # the grid's route, unchanged
    assert "profit_bars_reached" not in (state.get("flags") or {})
    e = _memory()["runs"][RUN_ID]
    assert e["profit_bars"]["result"] == "FAIL" and e["profit_bars"]["passing"] == []


def test_idea_status_grid_and_ledger_untouched_by_the_check():
    _set_orchestrator({**FULL_ON, **VARIANT_LOOP_ON})
    _write_bars()
    run_dir = _variant_run({"base": False, "design": True})
    arts = run_dir / "artifacts"
    watched = [arts / "idea_status.yaml", arts / "grid_evaluation.yaml",
               rpr.CAMPAIGN_STATE_PATH, arts / "variants" / "index.yaml"]
    before = {p: p.read_bytes() for p in watched}
    assert rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)["passing"] == ["design"]
    assert rpr._profit_bars_stop_route(run_dir, RUN_ID) == "human_pause"
    assert {p: p.read_bytes() for p in watched} == before
    assert rpr.load_yaml(arts / "idea_status.yaml")["idea_status"] == "refuted"


def test_component_error_run_pauses_for_the_fault_not_the_profit_stop(monkeypatch):
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    pr = rpr.load_yaml(run_dir / "artifacts" / "protocol_result.yaml")
    pr["results"][0]["component_errors"] = {"count": 3, "samples": []}
    rpr.save_yaml(run_dir / "artifacts" / "protocol_result.yaml", pr)
    rpr.run_loop(RUN_ID)
    state = _state(run_dir)
    assert state["flags"].get("component_execution_error_flagged") is True
    assert "profit_bars_reached" not in state["flags"]


# ---------------------------------------------------------------------------
# 6. Campaign memory
# ---------------------------------------------------------------------------

def test_memory_filled_per_variant_when_on():
    _set_orchestrator({**FULL_ON, **VARIANT_LOOP_ON})
    _write_bars()
    run_dir = _variant_run({"base": False, "design": True})
    rpr._mark_trial_invalidated(f"{RUN_ID}:base", "conformance")
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    rpr._run_regroup_record_stage(RUN_ID, run_dir, profit_bars_evaluated=True)
    doc = _memory()
    e = doc["runs"][RUN_ID]
    pb = e["profit_bars"]
    assert e["profit_bars_reason"] is None
    assert pb["scope"] == "every_backtest" and pb["passing"] == ["design"]
    assert set(pb["variants"]) == set(e["variants"]) == {"asset", "base", "broken", "design"}
    assert pb["variants"]["base"] == {"result": "INVALIDATED", "bars": {}}
    assert pb["variants"]["asset"] == {"result": "NOT_TESTED", "bars": {}}
    assert pb["variants"]["design"]["bars"]["sharpe_min"] == {"result": "PASS", "actual": 1.4,
                                                               "threshold": 0.5}
    assert e["idea_status"] == "refuted"
    jsonschema.Draft202012Validator(_SCHEMA).validate(doc)


def test_memory_null_and_reason_when_off():
    _set_orchestrator(ALL_ON)
    run_dir = _seed(idea_status="refuted")
    rpr._run_regroup_record_stage(RUN_ID, run_dir)
    doc = _memory()
    e = doc["runs"][RUN_ID]
    assert e["profit_bars"] is None and e["profit_bars_reason"] == cm.PROFIT_BARS_NOT_EVALUATED
    jsonschema.Draft202012Validator(_SCHEMA).validate(doc)


def test_schema_rejects_filled_profit_bars_with_a_reason():
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=False)
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    rpr._run_regroup_record_stage(RUN_ID, run_dir, profit_bars_evaluated=True)
    doc = _memory()
    jsonschema.Draft202012Validator(_SCHEMA).validate(doc)
    doc["runs"][RUN_ID]["profit_bars_reason"] = cm.PROFIT_BARS_NOT_EVALUATED
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.Draft202012Validator(_SCHEMA).validate(doc)


def test_memory_refuses_missing_evaluation_when_on():
    _set_orchestrator(FULL_ON)
    run_dir = _seed(idea_status="refuted")
    with pytest.raises(cm.CampaignMemoryError, match="profit_bars_evaluation.yaml is missing"):
        rpr._run_regroup_record_stage(RUN_ID, run_dir, profit_bars_evaluated=True)
    assert not _memory_path().exists()


def test_memory_refuses_promote_path_evaluation():
    _set_orchestrator(FULL_ON)
    run_dir = _seed(idea_status="refuted")
    rpr.save_yaml(run_dir / "artifacts" / "profit_bars_evaluation.yaml",
                  {"run_id": RUN_ID, "generated_at": "x", "bars": [], "result": "FAIL", "reasons": []})
    with pytest.raises(cm.CampaignMemoryError, match="scope"):
        rpr._run_regroup_record_stage(RUN_ID, run_dir, profit_bars_evaluated=True)


def test_memory_refuses_inconsistent_overall_result():
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=False)
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    path = run_dir / "artifacts" / "profit_bars_evaluation.yaml"
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    doc["result"] = "PASS"
    rpr.save_yaml(path, doc)
    with pytest.raises(cm.CampaignMemoryError, match="disagree"):
        rpr._run_regroup_record_stage(RUN_ID, run_dir, profit_bars_evaluated=True)


# ---------------------------------------------------------------------------
# 7. Promote-path coexistence
# ---------------------------------------------------------------------------

def _promote(run_dir: Path) -> str:
    rpr.save_yaml(run_dir / "artifacts" / "verdict_interpretation.yaml", {"hypothesis_id": "H-MEM-1"})
    return rpr._dispatch_verdict_route(run_dir, RUN_ID, {"hypothesis_verdict": "promote"},
                                       {"runs": [], "trial_sharpes": []}, "promote", None)


def _spy(monkeypatch, result: str = "PASS") -> list:
    calls = []

    def _fake(run_dir, run_id, **kw):
        calls.append(kw)
        return {"result": result, "bars": [], "reasons": []}
    monkeypatch.setattr(rpr, "_evaluate_profit_bars", _fake)
    return calls


def test_cr6_promote_path_skipped_only_with_this_runs_every_backtest_evaluation(monkeypatch):
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    before = (run_dir / "artifacts" / "profit_bars_evaluation.yaml").read_bytes()
    calls = _spy(monkeypatch)
    assert _promote(run_dir) == "holdout_evaluation"
    assert calls == []
    assert (run_dir / "artifacts" / "profit_bars_evaluation.yaml").read_bytes() == before
    assert "profit_bars_reached" not in (_state(run_dir).get("flags") or {})


def test_cr6_promote_path_runs_when_flag_on_but_no_every_backtest_evaluation(monkeypatch):
    """[CR 6] Flag on, but this run has no every_backtest evaluation (e.g. it
    reached protocol_execution before the flag): the promote path evaluates, with
    the avg-daily-return computation, and can pause."""
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=True)
    calls = _spy(monkeypatch)
    assert _promote(run_dir) == "human_pause"
    assert calls == [{"portfolio_basis": True}]


def test_cr4_promote_path_grades_avg_daily_return_only_with_the_flag():
    _write_bars()
    run_dir = _single_run(good=True)
    _set_orchestrator(FULL_ON)
    on = rpr._evaluate_profit_bars(run_dir, RUN_ID, portfolio_basis=True)
    off = rpr._evaluate_profit_bars(run_dir, RUN_ID)
    adr_on = {b["name"]: b for b in on["bars"]}["avg_daily_return_min"]
    adr_off = {b["name"]: b for b in off["bars"]}["avg_daily_return_min"]
    assert adr_on["result"] == "PASS" and adr_off["result"] == "NOT_EVALUABLE"
    # Flag on: the portfolio definitions, each row self-describing. Flag off: the
    # old rows exactly -- worst-coin drawdown, no basis key.
    assert {b["name"]: b["basis"] for b in on["bars"]} == _EXPECTED_BASIS
    assert all("basis" not in b for b in off["bars"])
    dd_off = {b["name"]: b for b in off["bars"]}["max_drawdown_pct_max"]
    assert dd_off["actual"] == 12.0 and dd_off["note"].endswith("worst symbol")


def test_promote_path_unchanged_without_the_new_flag(monkeypatch):
    _set_orchestrator({**ALL_ON, "profit_bars_file": {"enabled": True}})
    _write_bars()
    run_dir = _single_run(good=True)
    calls = _spy(monkeypatch)
    assert _promote(run_dir) == "human_pause"
    assert calls == [{}]  # the original two-argument call
    assert _state(run_dir)["flags"]["profit_bars_reached"] is True


def test_cr10_malformed_flag_on_promote_path_falls_back_to_holdout(monkeypatch):
    """[CR 10] The new flag is read inside the promote branch's try/except."""
    _set_orchestrator({**ALL_ON, "profit_bars_file": {"enabled": True},
                       "profit_bars_every_backtest": {"enabled": "yes"}})
    _write_bars()
    run_dir = _single_run(good=True)
    calls = _spy(monkeypatch)
    assert _promote(run_dir) == "holdout_evaluation"
    assert calls == []


# ---------------------------------------------------------------------------
# 8. Malformed bars file fails loud
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("doc", [
    {k: v for k, v in _VALID_BARS.items() if k != "sharpe_min"},
    {**_VALID_BARS, "trade_count_min": "thirty"},
    {**_VALID_BARS, "deflated_sharpe_threshold": True},
])
def test_malformed_bars_file_fails_loud_and_writes_nothing(doc):
    _set_orchestrator(FULL_ON)
    _write_bars(doc)
    run_dir = _single_run(good=True)
    with pytest.raises(rpr.ProfitabilityBarsSchemaError):
        rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)
    assert not (run_dir / "artifacts" / "profit_bars_evaluation.yaml").exists()


def test_missing_bars_file_fails_the_run_loudly(monkeypatch):
    run_dir, _stages, calls = _loop(monkeypatch, FULL_ON, good=True)
    state = _state(run_dir)
    assert state["status"] == "failed" and "profitability_bars.yaml" in state["last_error"]
    assert calls == []  # readers never ran on an ungraded backtest
    assert not (run_dir / "artifacts" / "profit_bars_evaluation.yaml").exists()


# ---------------------------------------------------------------------------
# 9. One scope constant; RUNBOOK resolution
# ---------------------------------------------------------------------------

def test_cr9_scope_constant_owned_by_campaign_memory(monkeypatch):
    assert not hasattr(rpr, "PROFIT_BARS_SCOPE_EVERY_BACKTEST")
    _set_orchestrator(FULL_ON)
    _write_bars()
    run_dir = _single_run(good=False)
    monkeypatch.setattr(cm, "PROFIT_BARS_SCOPE_EVERY_BACKTEST", "scope-from-campaign-memory")
    assert rpr._evaluate_profit_bars_every_backtest(run_dir, RUN_ID)["scope"] == \
        "scope-from-campaign-memory"


def test_cr5_runbook_has_a_separate_not_validated_resolution():
    text = (SR_ROOT / "docs" / "RUNBOOK.md").read_text(encoding="utf-8")
    row = next(line for line in text.splitlines() if line.startswith("| `profit_bars_reached` |"))
    assert "do NOT spend the holdout" in row
    assert "best of N" in row
    assert "`idea_status` refuted or inconclusive" in row
    assert "never re-run by a resume" in row
    assert "the readers have not run yet" not in row
