"""
E-037: USER_GUIDE.md's table of contents must stay current, and its internal
links must resolve.

WHY THIS EXISTS
---------------
Measured 2026-08-31: the hand-written TOC was 16 lines covering 8 of the guide's
92 headings, and listed **none** of the 13 stage blocks or the 30+ artifact
entries -- exactly the parts a reader or an agent goes looking for. A
hand-maintained index of 92 entries drifts within a week.

The TOC is now generated by `tools/gen_user_guide_toc.py`. This test is what
makes "generated" mean something: add a section, forget to regenerate, and the
suite fails with the command to run.

It also checks every internal `#anchor` resolves, which catches a heading being
reworded while links to it are left behind -- the same rot as a stale
`file:line`, one layer up.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_SR = Path(__file__).resolve().parent.parent
_GUIDE = _SR / "docs" / "USER_GUIDE.md"
_GEN = _SR / "tools" / "gen_user_guide_toc.py"


def _slug(text: str) -> str:
    """Mirror of the generator's rule; `_` is kept (valid in identifiers)."""
    t = text.strip().lower()
    t = re.sub(r"[`*]", "", t)
    t = re.sub(r"[^\w\s-]", "", t)
    return t.replace(" ", "-")


def test_toc_is_current() -> None:
    result = subprocess.run(
        [sys.executable, str(_GEN), "--check"],
        capture_output=True, text=True, cwd=str(_SR),
    )
    assert result.returncode == 0, (
        "USER_GUIDE.md's table of contents is out of date -- a heading was added, "
        "removed or reworded without regenerating it.\n"
        "    python strategy-research/tools/gen_user_guide_toc.py\n"
        f"{result.stdout}{result.stderr}"
    )


def test_internal_anchors_resolve() -> None:
    s = _GUIDE.read_text(encoding="utf-8")
    valid = {_slug(h) for h in re.findall(r"^#{2,4} (.+)$", s, re.M)}
    # Glossary terms are table rows, not headings, so they carry explicit HTML
    # anchors (<a id="g-..."></a>) to be linkable at their point of use.
    valid |= set(re.findall(r'<a id="([^"]+)"></a>', s))
    links = set(re.findall(r"\]\(#([^)]+)\)", s))
    broken = sorted(links - valid)
    assert not broken, (
        f"{len(broken)} internal link(s) in USER_GUIDE.md point at no heading: "
        f"{broken}\nA heading was reworded and the links to it were not updated."
    )


def test_stage_blocks_are_in_the_toc() -> None:
    """The 13 stage blocks are the most-consulted content; they must be indexed."""
    s = _GUIDE.read_text(encoding="utf-8")
    toc = s[s.index("<!-- TOC:START -->"): s.index("<!-- TOC:END -->")]
    stages = re.findall(r"^#### (Stage \d+ — `[a-z_]+`)", s, re.M)
    assert stages, "no stage blocks found -- has §2.2's heading style changed?"
    missing = [st for st in stages if f"#{_slug(st)}" not in toc]
    assert not missing, f"stage block(s) absent from the table of contents: {missing}"
