"""E-073 step 1 (D-081): the readers' subset of docs/DATA_DICTIONARY.md.

The v3 readers receive the five category reports, grid_evaluation.yaml,
claim_result_digest.yaml and claim_measurement.yaml, never bars.csv nor
trade_diagnostics.json itself. Under orchestrator.observable_backtest they get
docs/DATA_DICTIONARY_READERS.md: the full dictionary without the parts marked

    <!-- readers: omit -->
    ...
    <!-- /readers: omit -->

(section 1, bars.csv; the per-trade labels of trade_diagnostics.json that no
report carries). The full file stays for a reader of the raw files (E-075).

The readers' file is generated from the full one by `reader_subset` and
committed; tests/test_e073_data_dictionary.py fails when the committed file is
not exactly `reader_subset(full)`. Regenerate it with:

    python tools/data_dictionary.py        (from strategy-research/)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SR_ROOT = Path(__file__).resolve().parent.parent
FULL_DOC = SR_ROOT / "docs" / "DATA_DICTIONARY.md"
READERS_DOC = SR_ROOT / "docs" / "DATA_DICTIONARY_READERS.md"

OMIT_OPEN = "<!-- readers: omit -->"
OMIT_CLOSE = "<!-- /readers: omit -->"
_OMIT_RE = re.compile(re.escape(OMIT_OPEN) + r"\n.*?" + re.escape(OMIT_CLOSE) + r"\n", re.S)

READERS_NOTE = (
    "**Readers' subset, generated from `docs/DATA_DICTIONARY.md` by "
    "`tools/data_dictionary.py` (do not edit this file; edit the full one and "
    "regenerate).** Left out: section 1 (`bars.csv`, a file you do not receive) and "
    "the per-trade labels of `trade_diagnostics.json` (no report carries them). "
    "Sections 2 to 5 describe the blocks the category reports carry.\n")


def reader_subset(text: str) -> str:
    """The full dictionary without its `readers: omit` regions, with a note
    under the title. Raises on unbalanced or nested markers (a marker left in
    the output would hide or leak a section silently)."""
    opens = [m.start() for m in re.finditer(re.escape(OMIT_OPEN), text)]
    closes = [m.start() for m in re.finditer(re.escape(OMIT_CLOSE), text)]
    if not opens or len(opens) != len(closes) \
            or any(not o < c for o, c in zip(opens, closes)) \
            or any(not c < o for c, o in zip(closes, opens[1:])):
        raise ValueError(f"{FULL_DOC.name}: unbalanced or nested '{OMIT_OPEN}' markers "
                         f"({len(opens)} open, {len(closes)} close)")
    body = _OMIT_RE.sub("", text)
    if OMIT_OPEN in body or OMIT_CLOSE in body:
        raise ValueError(f"{FULL_DOC.name}: a '{OMIT_OPEN}' region is not on lines of its own")
    title, rest = body.split("\n", 1)
    return f"{title}\n\n{READERS_NOTE}{rest}"


def main() -> int:
    READERS_DOC.write_text(reader_subset(FULL_DOC.read_text(encoding="utf-8")),
                           encoding="utf-8", newline="\n")
    print(f"{READERS_DOC.relative_to(SR_ROOT)}: {READERS_DOC.stat().st_size} bytes "
          f"(full file {FULL_DOC.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
